### ISSUE TITLE
Provision Vireo installations on new QA and prod servers

### ISSUE THREAD

**Issue by kelynch** [pulibrary/dspace-development#280]
Provision `libtc201l` and `libtc101l` with Vireo installations, with 2021 Senior Data seeding database.

Original tickets for the OIT server requests are CHG0053820 and CHG0053821,

**Comment by jrgriffiniii** [comment]
https://princeton.service-now.com/service?id=ticket&table=incident&sys_id=bb5023921b5220108c9ebbb21a4bcbf2&view=sp is blocking my progress on `libtc100l.aws.princeton.edu`, however, this is *not* blocking my progress on `libtc201l.aws.princeton.edu`. I can continue with deploying the application in the latter environment.

**Comment by kelynch** [comment]
Per Kevin's update on the ticket, root access is working for `libtc101l`.

**Comment by jrgriffiniii** [comment]
The Vireo app. is now successfully running on port 9000 within the QA environment. I am going to proceed with installing the systemd scripts.

**Comment by jrgriffiniii** [comment]
I have opened https://princeton.service-now.com/service?id=ticket&table=incident&sys_id=1a7dedbe1b9a2810b69cca292a4bcbeb&view=sp in order to provide access to the QA servers. While I have been able to migrate the X.509 certificates from the 2020 server environments, there appear to be firewall restrictions at the AWS layer (`iptables` is not running) preventing me from accessing these servers.

**Comment by kelynch** [comment]
These servers were successfully provisioned and launched for March 22, 2021.
