### ISSUE TITLE
New Serials collection in DataSpace - Yishu

### ISSUE THREAD

**Issue by kelynch** [pulibrary/dspace-development#839]
Per Chiu-hui's request, create a collection for the Yishu serial.  Details below:

Collection Title: Serials and series reports (Access Limited to Princeton) - Yishu
Collection parent: https://dataspace.princeton.edu/handle/88435/dsp01r781wg06f 
Collection submission template should match 

![thumbnail_image002](https://github.com/user-attachments/assets/1d8bc936-294f-4270-ac90-a5a69113efd9)

## Acceptance criteria

- [ ] The new collection is created
- [ ] The new collection's submission form matches the above template
- [ ] The new collection's URL has been shared with Chiu-hui Huang and Debby Macdonald

**Comment by jrgriffiniii** [comment]
I apologize for the delay, however, I have been searching to understand precisely why this template was chosen. In order to advance this towards a resolution, I will simply copy this as I have in the past. Taking for example https://dataspace.princeton.edu/handle/88435/dsp018c97kq48z, I find:

```bash
dataspace_prod_db=> select h.handle,c.collection_id,c.template_item_id from handle as h inner join collection as c on c.collection_id = h.resource_id where h.handle='88435/dsp018c97kq48z';
        handle        | collection_id | template_item_id
----------------------+---------------+------------------
 88435/dsp018c97kq48z |           441 |             4058
(1 row)
```

Please note that this was used consistently for collection templates within the JRuby CLI (please see https://github.com/pulibrary/dspace-cli/blob/main/dspace/cli/serials_collection.rb#L27).

**Comment by jrgriffiniii** [comment]
An XML configuration file update was also required. Please see https://dataspace.princeton.edu/handle/88435/dsp019019s5852 and attempt to submit a new Item.

**Comment by kelynch** [comment]
This looks correct to me: 
![Screenshot 2024-09-03 at 4 31 46 PM](https://github.com/user-attachments/assets/e1293c8c-d2b5-4715-aebc-65653634583b)

Thank you James!

**Comment by jrgriffiniii** [comment]
The changes proposed by https://github.com/PrincetonUniversityLibrary/princeton-5/pull/96/files are required in order to ensure that this is resolved.

**Comment by kelynch** [comment]
Thank you, James!  I've followed up with Debby regarding this and reviewed the princeton-5 changed.  I'm going to close this ticket.
